### ISSUE TITLE
Delete Select an activity category option

### ISSUE THREAD

**Issue by corners2wall** [Pursottam6003/technodaya#5]
Delete Select an activity category option from dropdown
![Screenshot from 2023-09-15 19-59-44](https://github.com/Pursottam6003/technodaya/assets/110557519/6989dca0-0723-4495-a094-f5068bf4ea70)

**Comment by daknya** [comment]
What alternative can you suggest?

**Comment by corners2wall** [comment]
@daknya  It's redundant. When you click on it, the section is cleared. The same behavior can be achieved by adding a cross to the right side of the field. For example: 
![Screenshot from 2023-09-15 20-22-57](https://github.com/Pursottam6003/technodaya/assets/110557519/cb3967d1-023d-4f94-8c30-03d3bc2628de)

**Comment by tripathics** [comment]
@corners2wall what should be the initial state of the select then? BTW we were using basic HTML elements for inputs.

**Comment by corners2wall** [comment]
@tripathics In short, you don't should add placeholder in option
![image](https://github.com/Pursottam6003/technodaya/assets/110557519/4fc3413a-3861-4304-8415-0f8a210626c7)
